#----------------------------------------------------------------------
# This file was generated by C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\plugins\python-ce\helpers\pydev\pydevconsole.py
#
from wx.lib.embeddedimage import PyEmbeddedImage


