#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export PATH="${HERE}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
export PYTHONNOUSERSITE=1
unset PYTHONPATH
unset PYTHONHOME
exec "${HERE}/usr/bin/meerk40t" "$@"